name: .NET

on:
  push:
    tags:
      - "v*"
    branches: [ "master" ]
  pull_request:
      branches: [ "master" ]
      
env:
  NSIS_VERSION: 3.09

jobs:
    create_installer:
        runs-on: windows-latest

        steps:
        - name: Setup NSIS
          run: |
            Invoke-WebRequest https://nav.dl.sourceforge.net/project/nsis/NSIS%203/${{env.NSIS_VERSION}}/nsis-${{env.NSIS_VERSION}}-setup.exe -OutFile C:\WINDOWS\Temp\nsis-${{env.NSIS_VERSION}}-setup.exe
            Invoke-Expression "& C:\WINDOWS\Temp\nsis-${{env.NSIS_VERSION}}-setup.exe /S"

        - uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 9.0.x

        - name: Restore dependencies
          run: dotnet restore

        # Publish for x64 and x86
        - name: publish x64
          run: dotnet publish -c Release -r win-x64 --self-contained false --output "publish/x64"
        - name: publish x86
          run: dotnet publish -c Release -r win-x86 --self-contained false --output "publish/x86"

        # Create installer for x64 and x86
        - name: build x64 installer
          run: makensis /DARCH=x64 setup.nsi
        - name: build x86 installer
          run: makensis /DARCH=x86 setup.nsi


        - name: Upload x64 Build Artifact
          uses: actions/upload-artifact@v3.1.2
          with:
            name: setup-x64.exe
            path: setup-x64.exe

        - name: Upload x86 Build Artifact
          uses: actions/upload-artifact@v3.1.2
          with:
            name: setup-x86.exe
            path: setup-x86.exe

    release:
        runs-on: ubuntu-latest
        needs: create_installer
        steps:
        - uses: actions/checkout@v2

        - name: Download x64 installer
          uses: actions/download-artifact@v2
          with:
            name: setup-x64.exe

        - name: Download x86 installer
          uses: actions/download-artifact@v2
          with:
            name: setup-x86.exe

        - name: Rename x64 installer
          run: mv setup-x64.exe MastervolumeSync-${{ github.ref_name }}-Setup.exe

        - name: Rename x86 installer
          run: mv setup-x86.exe MastervolumeSync-${{ github.ref_name }}-x86-Setup.exe

        - name: Create Release
          uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: |
                MastervolumeSync-${{ github.ref_name }}-Setup.exe
                MastervolumeSync-${{ github.ref_name }}-x86-Setup.exe
            title: "MastervolumeSync ${{ github.ref_name }}"
